spring:
  application:
    name: covid19-backend
  datasource:
    url: jdbc:mysql://8.210.248.203/covid19
#    url: jdbc:mysql://localhost/covid19
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: covid19
    password: Database4.0!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#xunfei:
#  api-secret: 48a6e1905e5c869459f9b3b9e2a0b66f
#  api-key: 732e987ba7e0941db1c8ad4d257131df
#  app-id: 5e4e763f
#  host-url: https://iat-api.xfyun.cn/v2/iat

swagger:
  enable: true

session:
  max-day: 30

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

logging:
  # 是否记录详细的请求日志，默认为 false
  request: false
  level:
    root: info